# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flSXdpNlH6Mw4EZuch7zoTuYTV08KRHb
"""


import streamlit as st
import pandas as pd

# 读取数据
data = pd.read_csv('cleaned_text.csv')

# 创建一个文本输入框
search_text = st.text_input("请输入搜索内容:")

# 根据输入的文本检查是否存在
if search_text:
    # 检查输入是否匹配数据集中的任何一行
    if any(data['Domain'].str.contains(search_text, case=False)):
        st.write("数据库中已存在该SMB客户")
    else:
        st.write("数据库中不存在")
else:
    st.write("请输入搜索内容进行查询")
